[workspace]
members = ["iceberg-rust", "datafusion_iceberg"]

workspace.resolver = "2"

[workspace.dependencies]
object_store = { version = "0.7", features = ["aws", "gcp"] }
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
futures = "0.3.28"
async-trait = "0.1.68"
chrono = { version = "0.4.23", default-features = false, features = ["serde"] }
arrow = "46.0.0"
datafusion = "31.0.0"
parquet = { version = "46.0.0", features = ["async","object_store"] }
sqlparser = { version = "0.38.0", features = ["visitor"] }
thiserror = "1.0"
url = "^2.2"
itertools = "0.10.5"