[workspace]
members = ["iceberg-rust", "datafusion_iceberg", "datafusion_iceberg_catalog_rest", "iceberg_catalog_rest_client_rust","iceberg-c"]

[workspace.dependencies]  
anyhow = "1.0"
object_store = { version = "0.5.2", features = ["aws", "gcp"] }
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
futures = "0.3.26"
async-trait = "0.1.64"