[workspace]
members = ["iceberg-rust-spec", "iceberg-rust", "datafusion_iceberg", "iceberg-catalog-sql"]

workspace.resolver = "2"

[workspace.dependencies]
object_store = { version = "0.7", features = ["aws", "gcp"] }
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
futures = "0.3.28"
async-trait = "0.1"
chrono = { version = "0.4.23", default-features = false, features = ["serde"] }
arrow = "48.0.1"
arrow-schema = "48.0.1"
datafusion = "33.0.0"
parquet = { version = "48.0.1", features = ["async","object_store"] }
sqlparser = { version = "0.39.0", features = ["visitor"] }
thiserror = "1.0"
url = "^2.2"
itertools = "0.10.5"