[workspace]
members = [
  "iceberg-rust-spec",
  "iceberg-rust",
  "datafusion_iceberg",
  "datafusion-iceberg-sql",
  "iceberg-catalog-sql",
]


[workspace.dependencies]
object_store = { version = "0.7", features = ["aws", "gcp"] }
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
futures = "0.3.28"
async-trait = "0.1"
chrono = { version = "0.4.23", default-features = false, features = ["serde"] }
arrow = "48.0.1"
arrow-schema = "48.0.1"
datafusion = "33.0.0"
datafusion-sql = "33.0.0"
datafusion-expr = "33.0.0"
datafusion-common = "33.0.0"
parquet = { version = "48.0.1", features = ["async", "object_store"] }
sqlparser = { version = "0.39.0", features = ["visitor"] }
thiserror = "1.0"
url = "^2.2"
itertools = "0.10.5"
derive-getters = "0.3.0"
