[package]
name = "iceberg-rust"
version = "0.1.2"
edition = "2021"

description = "Rust implementation of Apache Iceberg"

license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
apache-avro = "0.14.0"
arrow = "34.0.0"
async-trait = { workspace = true }
bytes = "1.4.0"
chrono = { workspace = true }
futures = { workspace = true }
getrandom = "0.2.8"
itertools = "0.10.5"
murmur3 = "0.5.2"
object_store = { workspace = true }
parquet = { version = "34.0.0", features = ["async"] }
rust_decimal = "1.27.0"
serde = { workspace = true }
serde_derive = { workspace = true }
serde_bytes = "0.11.8"
serde_json = { workspace = true }
serde_repr = "0.1.10"
url = { workspace = true }
uuid = { version = "1.2.2", features = ["serde", "v4"] }

[dev-dependencies]
tokio = "1.21.0"
