[package]
name = "iceberg-rust"
version = "0.1.2"
edition = "2021"

description = "Rust implementation of Apache Iceberg"

license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apache-avro = "0.16.0"
arrow = "46.0.0"
async-trait = { workspace = true }
bytes = "1.4.0"
chrono = { workspace = true }
futures = { workspace = true }
getrandom = "0.2.8"
itertools = { workspace = true }
murmur3 = "0.5.2"
object_store = { workspace = true }
parquet = { version = "46.0.0", features = ["async","object_store"] }
rust_decimal = "1.27.0"
serde = { workspace = true }
serde_derive = { workspace = true }
serde_bytes = "0.11.8"
serde_json = { workspace = true }
serde_repr = "0.1.10"
url = { workspace = true }
uuid = { version = "1.3.2", features = ["serde", "v4","v1"] }
tokio = { version = "1.0", features = ["sync"] }
ordered-float = { version = "4.1.0", features = ["serde"] }
derive_builder = "0.12.0"
sqlparser = { version = "0.38.0", features = ["visitor"] }
thrift = { version = "0.17.0", default-features = false }
thiserror = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rusqlite = { version = "0.29", features = ["modern_sqlite"] }
