[package]
name = "datafusion-iceberg"
version = "0.1.2"
edition = "2021"

description = "TableProvider to Apache iceberg tables with Datafusion"

license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { workspace = true }
url = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
datafusion = { workspace = true }
chrono = { workspace = true }
object_store = { workspace = true }
iceberg-rust = { path = "../iceberg-rust", version = "0.1.3" }
iceberg-rust-spec = { path = "../iceberg-rust-spec", version = "0.1.0" }
itertools = { workspace = true }
dashmap = "5.4.0"
thiserror = { workspace = true }
tokio = { version = "1.0", features = ["sync"] }

[dev-dependencies]
tokio = "1"
iceberg-catalog-sql = { path = "../iceberg-catalog-sql" }
