[package]
name = "datafusion_iceberg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
url = "2.3.1"
serde_json = { workspace = true }
async-trait = { workspace = true }
datafusion = "18.0.0"
chrono = { version = "0.4.19", features = ["serde"] }
object_store = { workspace = true }
iceberg-rust = { path = "../iceberg-rust" }

[dev-dependencies]
tokio = "1.21"