[package]
name = "datafusion_iceberg"
version = "0.1.1"
edition = "2021"

description = "TableProvider to Apache iceberg tables with Datafusion"

license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
url = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
datafusion = { workspace = true }
chrono = { workspace = true }
object_store = { workspace = true }
iceberg-rust = { path = "../iceberg-rust" }

[dev-dependencies]
tokio = "1.21"